notifications:
  email: false
git:
  quiet: true
  depth: 1

language: java
python: 3

service:
- docker

addons:
  apt:
    update: true
    packages:
    - sudo
    - lsof
    - wget
    - bash
    - curl
    - jq
    - docker-ce
    - python3-dev
    - python3-pip
    - python3-six
    - python3-setuptools

install: true
before_install:
- docker-compose -v
- export PATH=$HOME/.local/bin:$PATH
- pip3 install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
- pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
- http --version --debug
- docker-compose -v
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 80 8001 8002 8080 5432

jobs:
  include:

  - stage: test
    name: microprofile-jpa
    jdk: openjdk8
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f microprofile-jpa/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/microprofile-jpa/target/*-all.jar  &
    - wait_for 8080
    - http :8080/bank-account username=username balance=123.45
    - http :8080/bank-account
    - http :8080
    - http :8080/not-found ololo=trololo
    - http :8080 hello=world
    - http :8080/openapi
    - http :8080/openapi Accept:application/json
    - http :8080/health
    - http :8080/metrics
    - http :8080/metrics Accept:application/json
    - http :8080/static/microprofile-quickstart-integration-tests.http
    - stop_any 80 8080

  - stage: test
    name: microprofile-quickstart
    jdk: openjdk8
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f microprofile-quickstart/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/microprofile-quickstart/target/*-all.jar  &
    - wait_for 8080
    - http :8080
    - http :8080/not-found ololo=trololo
    - http :8080 hello=world
    - http :8080/openapi
    - http :8080/health
    - http :8080/metrics
    - http :8080/metrics "Accept:application/json"
    - http :8080/static/microprofile-quickstart-integration-tests.http
    - http put :8080
    - stop_any 80 8080

  - stage: test
    name: config-quickstart
    jdk: openjdk8
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f config-quickstart/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/config-quickstart/target/*-all.jar  &
    - wait_for 8080
    - http :8080/conf ololo=ololooo
    - stop_any 80 8080

  - stage: test
    name: grpc-server-quickstart
    jdk: openjdk8
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f grpc-server-quickstart/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/grpc-server-quickstart/target/*-all.jar  &
    - wait_for 8080
    - http :8080 || echo 'should fail'
    - stop_any 80 8080

  - stage: test
    name: web-server-jersey-jsonp
    jdk: openjdk8
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f web-server-jersey-jsonp/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/web-server-jersey-jsonp/target/*-all.jar  &
    - wait_for 8080
    - http :8080
    - http put :8080/test-fallback
    - http post :8080 hello=world
    - stop_any 80 8080

  - stage: test
    name: web-server-jersey-quickstart
    jdk: openjdk8
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f web-server-jersey-quickstart/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/web-server-jersey-quickstart/target/*-all.jar  &
    - wait_for 8080
    - http :8080
    - http put :8080/test-fallback
    - stop_any 80 8080

  - stage: test
    name: web-server-quickstart
    jdk: openjdk8
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f web-server-quickstart/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/web-server-quickstart/target/*-all.jar  &
    - wait_for 8080
    - http :8080
    - stop_any 80 8080

  - stage: test
    jdk: openjdk8
    name: check updates
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U

  - stage: test
    name: mvn
    jdk: openjdk8
    script: cd $TRAVIS_BUILD_DIR && ./mvnw

  - stage: test
    name: microprofile-jpa jdk11
    jdk: openjdk11
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f microprofile-jpa/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/microprofile-jpa/target/*-all.jar  &
    - wait_for 8080
    - http :8080/bank-account username=username balance=123.45
    - http :8080/bank-account
    - http :8080
    - http :8080/not-found ololo=trololo
    - http :8080 hello=world
    - http :8080/openapi
    - http :8080/openapi Accept:application/json
    - http :8080/health
    - http :8080/metrics
    - http :8080/metrics Accept:application/json
    - http :8080/static/microprofile-quickstart-integration-tests.http
    - stop_any 80 8080

  - stage: test
    name: microprofile-quickstart jdk11
    jdk: openjdk11
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f microprofile-quickstart/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/microprofile-quickstart/target/*-all.jar  &
    - wait_for 8080
    - http :8080
    - http :8080/not-found ololo=trololo
    - http :8080 hello=world
    - http :8080/openapi
    - http :8080/health
    - http :8080/metrics
    - http :8080/metrics "Accept:application/json"
    - http :8080/static/microprofile-quickstart-integration-tests.http
    - http put :8080
    - stop_any 80 8080

  - stage: test
    name: config-quickstart jdk11
    jdk: openjdk11
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f config-quickstart/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/config-quickstart/target/*-all.jar  &
    - wait_for 8080
    - http :8080/conf ololo=ololooo
    - stop_any 80 8080

  - stage: test
    name: grpc-server-quickstart jdk11
    jdk: openjdk11
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f grpc-server-quickstart/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/grpc-server-quickstart/target/*-all.jar  &
    - wait_for 8080
    - http :8080 || echo 'should fail'
    - stop_any 80 8080

  - stage: test
    name: web-server-jersey-jsonp jdk11
    jdk: openjdk11
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f web-server-jersey-jsonp/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/web-server-jersey-jsonp/target/*-all.jar  &
    - wait_for 8080
    - http :8080
    - http put :8080/test-fallback
    - http post :8080 hello=world
    - stop_any 80 8080

  - stage: test
    name: web-server-jersey-quickstart jdk11
    jdk: openjdk11
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f web-server-jersey-quickstart/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/web-server-jersey-quickstart/target/*-all.jar  &
    - wait_for 8080
    - http :8080
    - http put :8080/test-fallback
    - stop_any 80 8080

  - stage: test
    name: web-server-quickstart jdk11
    jdk: openjdk11
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f web-server-quickstart/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/web-server-quickstart/target/*-all.jar  &
    - wait_for 8080
    - http :8080
    - stop_any 80 8080

  - stage: test
    jdk: openjdk11
    name: check updates jdk11
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U

  - stage: test
    name: mvn jdk11
    jdk: openjdk11
    script: cd $TRAVIS_BUILD_DIR && ./mvnw

cache:
  directories:
  - ~/.m2
  packages: true
  pip: true
