notifications:
  email: false
git:
  quiet: true
  depth: 1

env:
  global:
  - TERM=dumb

language: java
jdk:
- openjdk8
- openjdk11

python: 3

services: docker

addons:
  apt:
    update: true
    packages:
    - jq
    - bash
    - sudo
    - lsof
    - wget
    - curl
    - unzip
    - docker-ce
    - python3-pip

install: true
before_install:
- export PATH=$HOME/.local/bin:$PATH
- pip3 install --user $(whoami) --upgrade pip
- pip install --user $(whoami) --upgrade httpie
- http --version --debug
#- pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
- docker-compose -v
#
- source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
- stop_any 80 8080 5672 5432 27017 >/dev/null

jobs:
  include:

  - stage: test
    name: web-server-quickstart
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f web-server-quickstart/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/web-server-quickstart/target/*-all.jar  &
    - wait_for 8080
    - http :8080
    - stop_any 80 8080

  - stage: test
    name: check updates jdk11
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U

  - stage: test
    name: mvn
    script: cd $TRAVIS_BUILD_DIR && ./mvnw

cache:
  directories:
  - ~/.m2
  packages: true
  pip: true
