notifications:
  email: false
git:
  quiet: true
  depth: 1

language: java
python: 3

service:
- docker

addons:
  apt:
    update: true
    packages:
    - sudo
    - lsof
    - wget
    - bash
    - curl
    - jq
    - docker-ce
    - python3-dev
    - python3-pip
    - python3-six
    - python3-setuptools

install: true
before_install:
- docker-compose -v
- export PATH=$HOME/.local/bin:$PATH
- pip3 install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
- pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
- http --version --debug
- docker-compose -v
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 80 8001 8002 8080 5432

jobs:
  include:

  - stage: test
    name: web-server-quickstart
    jdk: openjdk8
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f web-server-quickstart/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/web-server-quickstart/target/*-all.jar  &
    - wait_for 8080
    - http :8080
    - stop_any 80 8080

  - stage: test
    jdk: openjdk8
    name: check updates
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U

  - stage: test
    name: mvn
    jdk: openjdk8
    script: cd $TRAVIS_BUILD_DIR && ./mvnw

  - stage: test
    name: web-server-quickstart
    jdk: openjdk11
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f web-server-quickstart/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/web-server-quickstart/target/*-all.jar  &
    - wait_for 8080
    - http :8080
    - stop_any 80 8080

  - stage: test
    jdk: openjdk11
    name: check updates
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -U

  - stage: test
    name: mvn
    jdk: openjdk11
    script: cd $TRAVIS_BUILD_DIR && ./mvnw

cache:
  directories:
  - ~/.m2
  packages: true
  pip: true
