GET http://127.0.0.1:8080
Content-Type: application/json
Accept: application/json

###
POST http://127.0.0.1:8080/test-fallback
Called-By: human

{}

###
GET http://127.0.0.1:8080
Content-Type: application/xml
Accept: application/xml

###
