GET http://127.0.0.1:8080
Content-Type: application/json
Accept: application/json

###
POST http://127.0.0.1:8080/test-fallback
Called-By: human
Accept: application/json
Content-Type: application/json

{
  "ololo": "trololo"
}

###
POST http://127.0.0.1:8080
Called-By: human
Accept: application/json
Content-Type: application/json

{
  "hello": "world"
}

###
GET http://127.0.0.1:8080/openapi

###
GET http://127.0.0.1:8080/health

###

GET http://127.0.0.1:8080/swagger/

###
